ALTER TABLE game_scores ADD COLUMN nmiss INTEGER NOT NULL DEFAULT 0;
ALTER TABLE game_scores ADD COLUMN n50 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE game_scores ADD COLUMN n100 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE game_scores ADD COLUMN n300 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE game_scores ADD COLUMN ngeki INTEGER NOT NULL DEFAULT 0;
ALTER TABLE game_scores ADD COLUMN nkatu INTEGER NOT NULL DEFAULT 0;
